lista_personajes = [
    {
        "id": 355,
        "nombre": "Jason Bourne",
        "identidad": "Delta Uno",
        "alias": "n/a",
        "empresa": "n/a",
        "altura": 168,
        "peso": 85,
        "genero": "Male",
        "color_ojos": "n/a",
        "color_pelo": "n/a",
        "alineacion": "good",
        "inteligencia": 88,
        "fuerza": 12,
        "poder": 26
    },
    {
        "id": 650,
        "nombre": "T-800",
        "identidad": "Cyberdyne Systems Series 800 Terminator Model 101",
        "alias": "Terminator",
        "empresa": "Dark Horse Comics",
        "altura": 188,
        "peso": 176.0,
        "genero": "M",
        "color_ojos": "Red",
        "color_pelo": "n/a",
        "alineacion": "bad",
        "inteligencia": 75,
        "fuerza": 34,
        "poder": 73
    },
    {
        "id": 142,
        "nombre": "Bumblebee",
        "identidad": "Karen Beecher",
        "alias": "n/a",
        "empresa": "DC Comics",
        "altura": 170.0,
        "peso": 59.0,
        "genero": "F",
        "color_ojos": "Brown",
        "color_pelo": "Black",
        "alineacion": "good",
        "inteligencia": 63,
        "fuerza": 28,
        "poder": 47
    },
    {
        "id": 78,
        "nombre": "Ben 10",
        "identidad": "Benjamin Kirby Tennyson",
        "alias": "Ben Ten",
        "empresa": "DC Comics",
        "altura": 161.54,
        "peso": 62,
        "genero": "M",
        "color_ojos": "n/a",
        "color_pelo": "n/a",
        "alineacion": "good",
        "inteligencia": 10,
        "fuerza": 7,
        "poder": 90
    },
    {
        "id": 524,
        "nombre": "Power Girl",
        "identidad": "Kara Zor-L",
        "alias": "Karen Starr",
        "empresa": "DC Comics",
        "altura": 180.0,
        "peso": 81.0,
        "genero": "F",
        "color_ojos": "blue",
        "color_pelo": "blond",
        "alineacion": "good",
        "inteligencia": 94,
        "fuerza": 100,
        "poder": 100
    },
    {
        "id": 526,
        "nombre": "Predator",
        "identidad": "Yautja",
        "alias": "Yautja",
        "empresa": "Dark Horse Comics",
        "altura": 213.0,
        "peso": 234.0,
        "genero": "M",
        "color_ojos": "n/a",
        "color_pelo": "n/a",
        "alineacion": "bad",
        "inteligencia": 63,
        "fuerza": 30,
        "poder": 100
    },
    {
        "id": 540,
        "nombre": "Rambo",
        "identidad": "John Rambo",
        "alias": "Lone Wolf",
        "empresa": "n/a",
        "altura": 178.0,
        "peso": 83.0,
        "genero": "M",
        "color_ojos": "Brown",
        "color_pelo": "Black",
        "alineacion": "good",
        "inteligencia": 63,
        "fuerza": 14,
        "poder": 30
    },
    {
        "id": 574,
        "nombre": "Sauron",
        "identidad": "Sauron",
        "alias": "Sauron the Dark",
        "empresa": "J. R. R. Tolkien",
        "altura": 279.0,
        "peso": 150,
        "genero": "M",
        "color_ojos": "n/a",
        "color_pelo": "n/a",
        "alineacion": "bad",
        "inteligencia": 88,
        "fuerza": 85,
        "poder": 100
    },
    {
        "id": 70,
        "nombre": "Batman",
        "identidad": "Bruce Wayne",
        "alias": "Matches Malone",
        "empresa": "DC Comics",
        "altura": 188.0,
        "peso": 95.0,
        "genero": "Male",
        "color_ojos": "blue",
        "color_pelo": "black",
        "alineacion": "good",
        "inteligencia": 100,
        "fuerza": 26,
        "poder": 47
    },
    {
        "id": 711,
        "nombre": "White Canary",
        "identidad": "",
        "alias": "Sara Lance",
        "empresa": "DC Comics",
        "altura": 165,
        "peso": 65,
        "genero": "Female",
        "color_ojos": "Brown",
        "color_pelo": "Black",
        "alineacion": "bad",
        "inteligencia": 63,
        "fuerza": 7,
        "poder": 49
    },
    {
        "id": 655,
        "nombre": "Thanos",
        "identidad": "Thanos",
        "alias": "The Overmaster",
        "empresa": "Marvel Comics",
        "altura": 201.0,
        "peso": 443.0,
        "genero": "M",
        "color_ojos": "Red",
        "color_pelo": "No Hair",
        "alineacion": "bad",
        "inteligencia": 100,
        "fuerza": 100,
        "poder": 100
    },
    {
        "id": 286,
        "nombre": "Goblin Queen",
        "identidad": "Madelyne Jennifer Pryor",
        "alias": "Maddie",
        "empresa": "Marvel Comics",
        "altura": 168.0,
        "peso": 50.0,
        "genero": "Female",
        "color_ojos": "Green",
        "color_pelo": "Red",
        "alineacion": "bad",
        "inteligencia": 75,
        "fuerza": 10,
        "poder": 65
    },
    {
        "id": 156,
        "nombre": "Captain Marvel",
        "identidad": "Billy Batson",
        "alias": "Shazam",
        "empresa": "DC Comics",
        "altura": 193.0,
        "peso": 101.0,
        "genero": "M",
        "color_ojos": "Blue",
        "color_pelo": "Black",
        "alineacion": "good",
        "inteligencia": 88,
        "fuerza": 100,
        "poder": 100
    },
    {
        "id": 95,
        "nombre": "Black Adam",
        "identidad": "Teth-Adam",
        "alias": "Theo Adam",
        "empresa": "DC Comics",
        "altura": 191.0,
        "peso": 113.0,
        "genero": "M",
        "color_ojos": "Brown",
        "color_pelo": "Black",
        "alineacion": "bad",
        "inteligencia": 88,
        "fuerza": 100,
        "poder": 100
    },
    {
        "id": 502,
        "nombre": "One Punch Man",
        "identidad": "Saitama",
        "alias": "Caped Baldy",
        "empresa": "Shueisha",
        "altura": 175.0,
        "peso": 69.0,
        "genero": "M",
        "color_ojos": "n/a",
        "color_pelo": "No Hair",
        "alineacion": "good",
        "inteligencia": 38,
        "fuerza": 100,
        "poder": 55
    },
    {
        "id": 607,
        "nombre": "Snowbird",
        "identidad": "Narya",
        "alias": "Anne McKenzie-Thompson",
        "empresa": "Marvel Comics",
        "altura": 178.0,
        "peso": 49.0,
        "genero": "Female",
        "color_ojos": "White",
        "color_pelo": "Blond",
        "alineacion": "good",
        "inteligencia": 50,
        "fuerza": 32,
        "poder": 70
    },
    {
        "id": 387,
        "nombre": "Killer Frost",
        "identidad": "Caitlin Snow",
        "alias": "n/a",
        "empresa": "DC Comics",
        "altura": 162,
        "peso": 62,
        "genero": "Female",
        "color_ojos": "Blue",
        "color_pelo": "Blond",
        "alineacion": "bad",
        "inteligencia": 88,
        "fuerza": 10,
        "poder": 59
    },
    {
        "id": 341,
        "nombre": "Indiana Jones",
        "identidad": "Indiana Jones",
        "alias": "Indy",
        "empresa": "George Lucas",
        "altura": 183.0,
        "peso": 79.0,
        "genero": "M",
        "color_ojos": "n/a",
        "color_pelo": "n/a",
        "alineacion": "good",
        "inteligencia": 69,
        "fuerza": 10,
        "poder": 19
    },
    {
        "id": 327,
        "nombre": "Hit-Girl",
        "identidad": "Mindy McCready",
        "alias": "Hitgirl",
        "empresa": "Icon Comics",
        "altura": 163,
        "peso": 63,
        "genero": "F",
        "color_ojos": "Green",
        "color_pelo": "Blond",
        "alineacion": "good",
        "inteligencia": 56,
        "fuerza": 7,
        "poder": 27
    },
    {
        "id": 383,
        "nombre": "Kick-Ass",
        "identidad": "Dave Lizewski",
        "alias": "Kickass",
        "empresa": "Icon Comics",
        "altura": 180,
        "peso": 78,
        "genero": "M",
        "color_ojos": "Blue",
        "color_pelo": "Blond",
        "alineacion": "good",
        "inteligencia": 38,
        "fuerza": 10,
        "poder": 22
    },
    {
        "id": 287,
        "nombre": "Godzilla",
        "identidad": "Gojira",
        "alias": "God of Destruction",
        "empresa": "",
        "altura": 119000,
        "peso": 90000.0,
        "genero": "NB",
        "color_ojos": "n/a",
        "color_pelo": "n/a",
        "alineacion": "bad",
        "inteligencia": 44,
        "fuerza": 100,
        "poder": 100
    },
    {
        "id": 346,
        "nombre": "Iron Man",
        "identidad": "Tony Stark",
        "alias": "Iron Knight",
        "empresa": "Marvel Comics",
        "altura": 198.0,
        "peso": 191.0,
        "genero": "M",
        "color_ojos": "Blue",
        "color_pelo": "Black",
        "alineacion": "good",
        "inteligencia": 100,
        "fuerza": 85,
        "poder": 100
    },
    {
        "id": 367,
        "nombre": "John Constantine",
        "identidad": "John Constantine",
        "alias": "Hellblazer",
        "empresa": "DC Comics",
        "altura": 183.0,
        "peso": 83,
        "genero": "M",
        "color_ojos": "Blue",
        "color_pelo": "Blond",
        "alineacion": "good",
        "inteligencia": 63,
        "fuerza": 10,
        "poder": 54
    },
    {
        "id": 253,
        "nombre": "Faora",
        "identidad": "Faora Hu-Ul",
        "alias": "Katie",
        "empresa": "DC Comics",
        "altura": 177,
        "peso": 57,
        "genero": "Female",
        "color_ojos": "Blue",
        "color_pelo": "Brown",
        "alineacion": "bad",
        "inteligencia": 88,
        "fuerza": 95,
        "poder": 98
    },
    {
        "id": 176,
        "nombre": "Chuck Norris",
        "identidad": "Carlos Ray Norris",
        "alias": "Chuck",
        "empresa": "n/a",
        "altura": 178.0,
        "peso": 72,
        "genero": "Male",
        "color_ojos": "Blue",
        "color_pelo": "Brown",
        "alineacion": "good",
        "inteligencia": 50,
        "fuerza": 80,
        "poder": 42
    },
    {
        "id": 98,
        "nombre": "Black Canary",
        "identidad": "Dinah Drake Lance",
        "alias": "n/a",
        "empresa": "DC Comics",
        "altura": 165.0,
        "peso": 58.0,
        "genero": "Female",
        "color_ojos": "Blue",
        "color_pelo": "Blond",
        "alineacion": "good",
        "inteligencia": 63,
        "fuerza": 8,
        "poder": 45
    },
    {
        "id": 627,
        "nombre": "Spock",
        "identidad": "S'chn T'gai Spock",
        "alias": "n/a",
        "empresa": "Star Trek",
        "altura": 185.0,
        "peso": 81.0,
        "genero": "Male",
        "color_ojos": "Brown",
        "color_pelo": "Black",
        "alineacion": "good",
        "inteligencia": 81,
        "fuerza": 18,
        "poder": 56
    },
    {
        "id": 686,
        "nombre": "Vegeta",
        "identidad": "Vegeta",
        "alias": "Super Vegeta",
        "empresa": "Shueisha",
        "altura": 168.0,
        "peso": 73.0,
        "genero": "M",
        "color_ojos": "n/a",
        "color_pelo": "Black",
        "alineacion": "bad",
        "inteligencia": 81,
        "fuerza": 100,
        "poder": 100
    },
    {
        "id": 687,
        "nombre": "Venom",
        "identidad": "Eddie Brock",
        "alias": "n/a",
        "empresa": "Anti-Venom",
        "altura": 191.0,
        "peso": 117.0,
        "genero": "M",
        "color_ojos": "Blue",
        "color_pelo": "Strawberry Blond",
        "alineacion": "bad",
        "inteligencia": 75,
        "fuerza": 57,
        "poder": 86
    },
    {
        "id": 718,
        "nombre": "Wonder Girl",
        "identidad": "Cassandra Elizabeth Sandsmark",
        "alias": "Cassie Sandsmark",
        "empresa": "DC Comics",
        "altura": 165.0,
        "peso": 51.0,
        "genero": "Female",
        "color_ojos": "Blue",
        "color_pelo": "Blond",
        "alineacion": "good",
        "inteligencia": 75,
        "fuerza": 90,
        "poder": 39
    },
    {
        "id": 149,
        "nombre": "Captain America",
        "identidad": "Steve Rogers",
        "alias": "Nomad",
        "empresa": "Marvel Comics",
        "altura": 188.0,
        "peso": 108.0,
        "genero": "Male",
        "color_ojos": "blue",
        "color_pelo": "blond",
        "alineacion": "good",
        "inteligencia": 69,
        "fuerza": 19,
        "poder": 60
    },
    {
        "id": 204,
        "nombre": "Darkseid",
        "identidad": "Uxas",
        "alias": "Dark God",
        "empresa": "DC Comics",
        "altura": 267.0,
        "peso": 817.0,
        "genero": "M",
        "color_ojos": "Red",
        "color_pelo": "No Hair",
        "alineacion": "bad",
        "inteligencia": 88,
        "fuerza": 100,
        "poder": 100
    },
    {
        "id": 289,
        "nombre": "Goku",
        "identidad": "Kakarot",
        "alias": "Z-Fighter",
        "empresa": "Shueisha",
        "altura": 175.0,
        "peso": 62.0,
        "genero": "M",
        "color_ojos": "n/a",
        "color_pelo": "n/a",
        "alineacion": "good",
        "inteligencia": 56,
        "fuerza": 100,
        "poder": 100
    },
    {
        "id": 307,
        "nombre": "Han Solo",
        "identidad": "Han Solo",
        "alias": "n/a",
        "empresa": "George Lucas",
        "altura": 183.0,
        "peso": 79.0,
        "genero": "M",
        "color_ojos": "Brown",
        "color_pelo": "Brown",
        "alineacion": "good",
        "inteligencia": 50,
        "fuerza": 10,
        "poder": 43
    },
    {
        "id": 308,
        "nombre": "Hancock",
        "identidad": "John Hancock",
        "alias": "n/a",
        "empresa": "Sony Pictures",
        "altura": 188.0,
        "peso": 88,
        "genero": "M",
        "color_ojos": "Brown",
        "color_pelo": "Black",
        "alineacion": "good",
        "inteligencia": 63,
        "fuerza": 90,
        "poder": 100
    },
    {
        "id": 310,
        "nombre": "Harry Potter",
        "identidad": "Harry James Potter",
        "alias": "Quidditch Captain",
        "empresa": "J. K. Rowling",
        "altura": 168,
        "peso": 65,
        "genero": "M",
        "color_ojos": "Green",
        "color_pelo": "Black",
        "alineacion": "good",
        "inteligencia": 75,
        "fuerza": 7,
        "poder": 100
    },
    {
        "id": 485,
        "nombre": "Naruto Uzumaki",
        "identidad": "Naruto Uzumaki",
        "alias": "n/a",
        "empresa": "Shueisha",
        "altura": 168.0,
        "peso": 54.0,
        "genero": "M",
        "color_ojos": "n/a",
        "color_pelo": "n/a",
        "alineacion": "good",
        "inteligencia": 50,
        "fuerza": 80,
        "poder": 100
    }
]